[package]
name = "stwo-fibonacci"
version = "0.1.0"
edition = "2021"

[dependencies]
stwo-prover = { path = "../stwo/crates/prover"}
itertools = "0.12.0"
num-traits = "0.2.17"
rand = { version = "0.8.5", default-features = false, features = ["small_rng"] }
